blank_issues_enabled: true
contact_links:
  - name: Questions & Answers
    url: https://github.com/Xiaokang2022/tkintertools/discussions/categories/q-a
    about: Please ask and answer questions here.